'use strict';

/**
 * Dados das cartas do jogo base Deception: Murder in Hong Kong.
 * Cada carta tem um id, nome em inglês (EN, como no jogo físico) e tradução (PT).
 * As cartas de Pista (Clue) e Meio (Means) são PÚBLICAS durante a partida —
 * o segredo está apenas em QUAIS delas o assassino escolhe como solução.
 */

// [en, pt]
const MEANS_RAW = [
  ['Alcohol', 'Álcool'],
  ['Amoeba', 'Ameba'],
  ['Arsenic', 'Arsênico'],
  ['Arson', 'Incêndio criminoso'],
  ['Axe', 'Machado'],
  ['Bamboo Tip', 'Ponta de bambu'],
  ['Bat', 'Bastão'],
  ['Belt', 'Cinto'],
  ['Bite And Tear', 'Morder e rasgar'],
  ['Blender', 'Liquidificador'],
  ['Blood Release', 'Sangria'],
  ['Box Cutter', 'Estilete'],
  ['Brick', 'Tijolo'],
  ['Bury', 'Enterrar'],
  ['Candlestick', 'Castiçal'],
  ['Chainsaw', 'Motosserra'],
  ['Chemicals', 'Produtos químicos'],
  ['Cleaver', 'Cutelo'],
  ['Crutch', 'Muleta'],
  ['Dagger', 'Adaga'],
  ['Dirty Water', 'Água suja'],
  ['Dismember', 'Esquartejar'],
  ['Drill', 'Furadeira'],
  ['Drown', 'Afogar'],
  ['Dumbbell', 'Haltere'],
  ['E-Bike', 'Bicicleta elétrica'],
  ['Electric Baton', 'Cassetete elétrico'],
  ['Electric Current', 'Corrente elétrica'],
  ['Explosives', 'Explosivos'],
  ['Folding Chair', 'Cadeira dobrável'],
  ['Gunpowder', 'Pólvora'],
  ['Hammer', 'Martelo'],
  ['Hook', 'Gancho'],
  ['Ice Skates', 'Patins de gelo'],
  ['Illegal Drug', 'Droga ilegal'],
  ['Injection', 'Injeção'],
  ['Kerosene', 'Querosene'],
  ['Kick', 'Chute'],
  ['Knife And Fork', 'Faca e garfo'],
  ['Lighter', 'Isqueiro'],
  ['Liquid Drug', 'Droga líquida'],
  ['Locked Room', 'Quarto trancado'],
  ['Machete', 'Facão'],
  ['Machine', 'Máquina'],
  ['Mad Dog', 'Cachorro raivoso'],
  ['Match', 'Fósforo'],
  ['Mercury', 'Mercúrio'],
  ['Metal Chain', 'Corrente de metal'],
  ['Metal Wire', 'Arame'],
  ['Overdose', 'Overdose'],
  ['Packing Tape', 'Fita adesiva'],
  ['Pesticide', 'Pesticida'],
  ['Pill', 'Pílula'],
  ['Pillow', 'Travesseiro'],
  ['Pistol', 'Pistola'],
  ['Plague', 'Praga'],
  ['Plastic Bag', 'Saco plástico'],
  ['Poisonous Gas', 'Gás venenoso'],
  ['Poisonous Needle', 'Agulha envenenada'],
  ['Potted Plant', 'Vaso de planta'],
  ['Powder Drug', 'Droga em pó'],
  ['Punch', 'Soco'],
  ['Push', 'Empurrão'],
  ['Radiation', 'Radiação'],
  ['Razor Blade', 'Lâmina de barbear'],
  ['Rope', 'Corda'],
  ['Scarf', 'Cachecol'],
  ['Scissors', 'Tesoura'],
  ['Sculpture', 'Escultura'],
  ['Smoke', 'Fumaça'],
  ['Sniper', 'Sniper'],
  ['Starvation', 'Inanição'],
  ['Steel Tube', 'Tubo de aço'],
  ['Stone', 'Pedra'],
  ['Sulfuric Acid', 'Ácido sulfúrico'],
  ['Surgery', 'Cirurgia'],
  ['Throat Slit', 'Garganta cortada'],
  ['Towel', 'Toalha'],
  ['Trophy', 'Troféu'],
  ['Trowel', 'Colher de pedreiro'],
  ['Unarmed', 'Desarmado'],
  ['Venomous Scorpion', 'Escorpião venenoso'],
  ['Venomous Snake', 'Cobra venenosa'],
  ['Video Game Console', 'Videogame'],
  ['Virus', 'Vírus'],
  ['Whip', 'Chicote'],
  ['Wine', 'Vinho'],
  ['Wire', 'Fio'],
  ['Work', 'Esforço físico'],
  ['Wrench', 'Chave inglesa'],
];

// [en, pt]
const CLUES_RAW = [
  ['Air Conditioning', 'Ar-condicionado'],
  ['Ants', 'Formigas'],
  ['Antique', 'Antiguidade'],
  ['Apple', 'Maçã'],
  ['Badge', 'Distintivo'],
  ['Bandage', 'Atadura'],
  ['Banknote', 'Cédula de dinheiro'],
  ['Bell', 'Sino'],
  ['Betting Chips', 'Fichas de aposta'],
  ['Blood', 'Sangue'],
  ['Bone', 'Osso'],
  ['Book', 'Livro'],
  ['Bracelet', 'Pulseira'],
  ['Bread', 'Pão'],
  ['Briefs', 'Cueca'],
  ['Broom', 'Vassoura'],
  ['Bullet', 'Bala (projétil)'],
  ['Button', 'Botão'],
  ['Cake', 'Bolo'],
  ['Calendar', 'Calendário'],
  ['Candy', 'Doce'],
  ['Carton', 'Caixa de papelão'],
  ['Cassette Tape', 'Fita cassete'],
  ['Cat', 'Gato'],
  ['Certificate', 'Certificado'],
  ['Chalk', 'Giz'],
  ['Cigar', 'Charuto'],
  ['Cigarette Ash', 'Cinza de cigarro'],
  ['Cigarette Butt', 'Bituca de cigarro'],
  ['Cleaning Cloth', 'Pano de limpeza'],
  ['Cockroach', 'Barata'],
  ['Coffee', 'Café'],
  ['Coins', 'Moedas'],
  ['Comics', 'Quadrinhos'],
  ['Computer', 'Computador'],
  ['Computer Disk', 'Disquete'],
  ['Computer Mouse', 'Mouse'],
  ['Confidential Letter', 'Carta confidencial'],
  ['Cosmetic Mask', 'Máscara de beleza'],
  ['Cotton', 'Algodão'],
  ['Cup', 'Xícara'],
  ['Curtains', 'Cortinas'],
  ['Dentures', 'Dentadura'],
  ['Diamond', 'Diamante'],
  ['Diary', 'Diário'],
  ['Dice', 'Dados'],
  ['Dictionary', 'Dicionário'],
  ['Dirt', 'Sujeira / terra'],
  ['Documents', 'Documentos'],
  ['Dog Fur', 'Pelo de cachorro'],
  ['Dust', 'Poeira'],
  ['Earrings', 'Brincos'],
  ['Eggs', 'Ovos'],
  ['Electric Circuit', 'Circuito elétrico'],
  ['Envelope', 'Envelope'],
  ['Exam Paper', 'Prova'],
  ['Express Courier', 'Entrega expressa'],
  ['Fan', 'Ventilador'],
  ['Fax', 'Fax'],
  ['Fiber Optics', 'Fibra óptica'],
  ['Fingernails', 'Unhas'],
  ['Flashlight', 'Lanterna'],
  ['Flip-Flop', 'Chinelo'],
  ['Flute', 'Flauta'],
  ['Flyer', 'Panfleto'],
  ['Food Ingredients', 'Ingredientes'],
  ['Gear', 'Engrenagem'],
  ['Gift', 'Presente'],
  ['Gloves', 'Luvas'],
  ['Glue', 'Cola'],
  ['Graffiti', 'Grafite / pichação'],
  ['Hair', 'Cabelo'],
  ['Hairpin', 'Grampo de cabelo'],
  ['Handcuffs', 'Algemas'],
  ['Hanger', 'Cabide'],
  ['Hat', 'Chapéu'],
  ['Headset', 'Fone de ouvido'],
  ['Helmet', 'Capacete'],
  ['Herbal Medicine', 'Remédio herbal'],
  ['High Heel', 'Salto alto'],
  ['Hourglass', 'Ampulheta'],
  ['Ice', 'Gelo'],
  ['ID Card', 'Documento de identidade'],
  ['Ink', 'Tinta (caneta)'],
  ['Insect', 'Inseto'],
  ['Internet Cable', 'Cabo de internet'],
  ['Invitation Card', 'Convite'],
  ['IOU Note', 'Nota promissória'],
  ['Iron', 'Ferro de passar'],
  ['IV Bag', 'Bolsa de soro'],
  ['Jacket', 'Jaqueta'],
  ['Jewelry', 'Joias'],
  ['Juice', 'Suco'],
  ['Key', 'Chave'],
  ['Leaf', 'Folha'],
  ['Leather Bag', 'Bolsa de couro'],
  ['Leather Shoe', 'Sapato de couro'],
  ['Lens', 'Lente'],
  ['Light Bulb', 'Lâmpada'],
  ['Lipstick', 'Batom'],
  ['Lock', 'Cadeado'],
  ['Lottery Ticket', 'Bilhete de loteria'],
  ['Love Letter', 'Carta de amor'],
  ['Luggage', 'Bagagem'],
  ['Lunch Box', 'Marmita'],
  ['Magazine', 'Revista'],
  ['Mahjong Tiles', 'Peças de mahjong'],
  ['Map', 'Mapa'],
  ['Mark', 'Marca'],
  ['Mask', 'Máscara'],
  ['Maze', 'Labirinto'],
  ['Menu', 'Cardápio'],
  ['Mirror', 'Espelho'],
  ['Mobile Phone', 'Celular'],
  ['Model', 'Modelo / maquete'],
  ['Mosquito', 'Mosquito'],
  ['Mosquito Coil', 'Espiral anti-mosquito'],
  ['Nail', 'Prego'],
  ['Name Card', 'Cartão de visita'],
  ['Necklace', 'Colar'],
  ['Needle And Thread', 'Agulha e linha'],
  ['Newspaper', 'Jornal'],
  ['Note', 'Bilhete / nota'],
  ['Notebook', 'Caderno'],
  ['Numbers', 'Números'],
  ['Office Supplies', 'Material de escritório'],
  ['Oil Painting', 'Pintura a óleo'],
  ['Oil Stain', 'Mancha de óleo'],
  ['Paint', 'Tinta'],
  ['Panties', 'Calcinha'],
  ['Peanut', 'Amendoim'],
  ['Perfume', 'Perfume'],
  ['Photograph', 'Fotografia'],
  ['Plant', 'Planta'],
  ['Plastic', 'Plástico'],
  ['Playing Cards', 'Baralho'],
  ['Pocket Watch', 'Relógio de bolso'],
  ['Postal Stamp', 'Selo postal'],
  ['Powder', 'Pó'],
  ['Prescription', 'Receita médica'],
  ['Puppet', 'Marionete'],
  ['Push Pin', 'Tacha / alfinete'],
  ['Puzzle', 'Quebra-cabeça'],
  ['Raincoat', 'Capa de chuva'],
  ['Rat', 'Rato'],
  ['Receipt', 'Recibo'],
  ['Red Wine', 'Vinho tinto'],
  ['Riddle', 'Charada'],
  ['Ring', 'Anel'],
  ['Rose', 'Rosa'],
  ['Rubber Stamp', 'Carimbo'],
  ['Sack', 'Saco'],
  ['Safety Pin', 'Alfinete de segurança'],
  ['Sand', 'Areia'],
  ['Sawdust', 'Serragem'],
  ['Seasoning', 'Tempero'],
  ['Signature', 'Assinatura'],
  ['Skull', 'Crânio'],
  ['Snacks', 'Salgadinhos'],
  ['Soap', 'Sabonete'],
  ['Sock', 'Meia'],
  ['Soft Drink', 'Refrigerante'],
  ['Speaker', 'Caixa de som'],
  ['Specimen', 'Amostra'],
  ['Spider', 'Aranha'],
  ['Spinning Top', 'Pião'],
  ['Sponge', 'Esponja'],
  ['Spring', 'Mola'],
  ['Steamed Buns', 'Pãezinhos no vapor'],
  ['Stockings', 'Meia-calça'],
  ['Stuffed Toy', 'Bicho de pelúcia'],
  ['Suit', 'Terno'],
  ['Sunglasses', 'Óculos de sol'],
  ['Surgical Mask', 'Máscara cirúrgica'],
  ['Surveillance Camera', 'Câmera de vigilância'],
  ['Switch', 'Interruptor'],
  ['Syringe', 'Seringa'],
  ['Table Lamp', 'Abajur'],
  ['Take-Out', 'Comida para viagem'],
  ['Tattoo', 'Tatuagem'],
  ['Tea Leaves', 'Folhas de chá'],
  ['Telephone', 'Telefone'],
  ['Test Tube', 'Tubo de ensaio'],
  ['Tie', 'Gravata'],
  ['Timber', 'Madeira / tora'],
  ['Tissue', 'Lenço de papel'],
  ['Tool Box', 'Caixa de ferramentas'],
  ['Toothpicks', 'Palitos de dente'],
  ['Toy', 'Brinquedo'],
  ['Toy Blocks', 'Blocos de montar'],
  ['Tweezers', 'Pinça'],
  ['Umbrella', 'Guarda-chuva'],
  ['Uniform', 'Uniforme'],
  ['USB Flash Drive', 'Pendrive'],
  ['Vegetables', 'Legumes'],
  ['Video Camera', 'Filmadora'],
  ['Violin', 'Violino'],
  ['Wallet', 'Carteira'],
  ['Watch', 'Relógio de pulso'],
  ['Wig', 'Peruca'],
];

// Scene tiles (usados pelo Cientista Forense). Título + 6 opções (PT).
const SCENE_TILES = {
  causeOfDeath: {
    key: 'causeOfDeath',
    title: { en: 'Cause of Death', pt: 'Causa da Morte' },
    fixed: true,
    options: ['Asfixia', 'Ferimento grave', 'Perda de sangue', 'Doença', 'Envenenamento', 'Acidente'],
  },
  location: {
    key: 'location',
    title: { en: 'Location of Crime', pt: 'Local do Crime' },
    fixed: true,
    groups: [
      ['Sala', 'Quarto', 'Depósito', 'Banheiro', 'Cozinha', 'Varanda'],
      ['Casa de veraneio', 'Parque', 'Supermercado', 'Escola', 'Mata', 'Banco'],
      ['Bar', 'Livraria', 'Restaurante', 'Hotel', 'Hospital', 'Obra'],
      ['Parquinho', 'Sala de aula', 'Dormitório', 'Refeitório', 'Elevador', 'Banheiro público'],
    ],
  },
  details: [
    { key: 'motive', title: { en: 'Motive of Crime', pt: 'Motivo do crime' }, options: ['Ódio', 'Poder', 'Dinheiro', 'Amor', 'Ciúme', 'Justiça'] },
    { key: 'weather', title: { en: 'Weather', pt: 'Clima' }, options: ['Ensolarado', 'Tempestade', 'Seco', 'Úmido', 'Frio', 'Quente'] },
    { key: 'corpseHint', title: { en: 'Hint on Corpse', pt: 'Indício no corpo' }, options: ['Cabeça', 'Peito', 'Mão', 'Perna', 'Parcial', 'Todo o corpo'] },
    { key: 'impression', title: { en: 'General Impression', pt: 'Impressão geral' }, options: ['Comum', 'Criativo', 'Suspeito', 'Cruel', 'Horrível', 'Suspense'] },
    { key: 'corpseCondition', title: { en: 'Corpse Condition', pt: 'Estado do corpo' }, options: ['Ainda quente', 'Rígido', 'Decomposto', 'Incompleto', 'Intacto', 'Retorcido'] },
    { key: 'victimIdentity', title: { en: "Victim's Identity", pt: 'Identidade da vítima' }, options: ['Criança', 'Jovem adulto', 'Meia-idade', 'Idoso', 'Masculino', 'Feminino'] },
    { key: 'murdererPersonality', title: { en: "Murderer's Personality", pt: 'Personalidade do assassino' }, options: ['Arrogante', 'Desprezível', 'Furioso', 'Ganancioso', 'Brutal', 'Perverso'] },
    { key: 'sceneState', title: { en: 'State of The Scene', pt: 'Estado da cena' }, options: ['Em pedaços', 'Cinzas', 'Mancha de água', 'Rachado', 'Desordenado', 'Arrumado'] },
    { key: 'victimBuild', title: { en: "Victim's Build", pt: 'Compleição da vítima' }, options: ['Grande', 'Magro', 'Alto', 'Baixo', 'Desfigurado', 'Em forma'] },
    { key: 'victimClothes', title: { en: "Victim's Clothes", pt: 'Roupas da vítima' }, options: ['Arrumadas', 'Desarrumadas', 'Elegantes', 'Surradas', 'Bizarras', 'Nua'] },
    { key: 'evidenceLeft', title: { en: 'Evidence Left Behind', pt: 'Evidência deixada' }, options: ['Natural', 'Artística', 'Escrita', 'Sintética', 'Pessoal', 'Sem relação'] },
    { key: 'victimExpression', title: { en: "Victim's Expression", pt: 'Expressão da vítima' }, options: ['Serena', 'Lutando', 'Assustada', 'Com dor', 'Vazia', 'Brava'] },
    { key: 'timeOfDeath', title: { en: 'Time of Death', pt: 'Hora da morte' }, options: ['Amanhecer', 'Manhã', 'Meio-dia', 'Tarde', 'Noite', 'Meia-noite'] },
    { key: 'duration', title: { en: 'Duration of Crime', pt: 'Duração do crime' }, options: ['Instantâneo', 'Breve', 'Gradual', 'Prolongado', 'Alguns dias', 'Incerto'] },
    { key: 'trace', title: { en: 'Trace at the Scene', pt: 'Vestígio na cena' }, options: ['Impressão digital', 'Pegada', 'Contusão', 'Mancha de sangue', 'Fluido corporal', 'Cicatriz'] },
    { key: 'bystander', title: { en: 'Noticed by Bystander', pt: 'Percebido por testemunha' }, options: ['Som súbito', 'Som prolongado', 'Cheiro', 'Visual', 'Ação', 'Nada'] },
    { key: 'relationship', title: { en: 'Social Relationship', pt: 'Relação social' }, options: ['Parentes', 'Amigos', 'Colegas', 'Patrão/Empregado', 'Amantes', 'Estranhos'] },
    { key: 'occupation', title: { en: "Victim's Occupation", pt: 'Ocupação da vítima' }, options: ['Chefe', 'Profissional liberal', 'Operário', 'Estudante', 'Desempregado', 'Aposentado'] },
    { key: 'inProgress', title: { en: 'In Progress', pt: 'Em andamento' }, options: ['Entretenimento', 'Relaxamento', 'Reunião', 'Negócio', 'Visita', 'Jantar'] },
    { key: 'incident', title: { en: 'Sudden Incident', pt: 'Incidente súbito' }, options: ['Queda de energia', 'Incêndio', 'Conflito', 'Perda de valores', 'Grito', 'Nada'] },
    { key: 'dayOfCrime', title: { en: 'Day of Crime', pt: 'Dia do crime' }, options: ['Dia de semana', 'Fim de semana', 'Primavera', 'Verão', 'Outono', 'Inverno'] },
  ],
};

function makeDeck(raw, prefix) {
  return raw.map(([en, pt], i) => ({ id: `${prefix}${String(i + 1).padStart(3, '0')}`, en, pt }));
}

const MEANS = makeDeck(MEANS_RAW, 'm');
const CLUES = makeDeck(CLUES_RAW, 'c');

module.exports = { MEANS, CLUES, SCENE_TILES, MEANS_RAW, CLUES_RAW };
